# Generated by Django 2.2.5 on 2019-09-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parimatch',
            options={'ordering': ['total'], 'verbose_name': 'Игра parimatch.ru', 'verbose_name_plural': 'Игры parimatch.ru'},
        ),
        migrations.RemoveField(
            model_name='parimatch',
            name='kindofsport',
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='parimatch',
            name='game',
            field=models.CharField(max_length=200, verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='parimatch',
            name='league',
            field=models.CharField(max_length=200, verbose_name='Лига'),
        ),
    ]
